### ISSUE TITLE
test_single.ply

### ISSUE THREAD

**Issue by Super-Iron-Man** [c-sommer/orthogonal-planes#1]
sorry,I cant find the data/test_single.ply

**Comment by yuecideng** [comment]
Hi, I build your code successfully but run with bugs as be
![Screenshot from 2020-07-22 17-04-28](https://user-images.githubusercontent.com/42235877/88157549-7bc80980-cc3d-11ea-9ea3-6ad802aeea52.png)
![image](https://user-images.githubusercontent.com/42235877/88157623-939f8d80-cc3d-11ea-8a0c-b01b587c30ed.png)

The `ply` files I have saved to `data` folder, could you help me solve this problem, thanks

**Comment by c-sommer** [comment]
@Super-Iron-Man I am very sorry for not providing the test ply file, it was due to .ply being on my gitignore (done now).
@yuecideng Mostly the segmentation faults are experienced when the provided ply file has the wrong "format", i.e. it is not single precision or normals are missing. Could this be the reason for your problem?

**Comment by benchun123** [comment]
@c-sommer Hi Sommer, thanks a lot for your great work, I am interested in plane refinement, from the paper, we can get a good result from optimization, I would like to ask if the point cloud should be in good quality. For example, if one plane is incomplete, can this algorithm still be refined? 

I also want to try the code, easy to build, but problems happen when testing the data, it seems the loading ply is okay, but failed to build plane graph, besides, the point cloud window is empty, while the ply is okay when opened by other software. 

![image](https://user-images.githubusercontent.com/32426078/115107160-6af8ba00-9f69-11eb-9e38-56d2015c1967.png)
![image](https://user-images.githubusercontent.com/32426078/115107179-8c59a600-9f69-11eb-81c6-c9942c0d564b.png)

**Comment by c-sommer** [comment]
Dear @benchun123 , Thanks a lot for your interest in the project and for notifying me about this issue!
I updated the `test_single.ply`. The prior version was unfortunately wrongly scaled. I also added the original ICL-NUIM `.png` file, so you can have a look at the original depth image yourself.
Some parameters in the `main.cpp` files were also updated accordingly, such that the algorithm should now return meaningful results with the default parameters (at least it does for me).
