### ISSUE TITLE
PLY file is garbled

### ISSUE THREAD

**Issue by tessamccain** [c-sommer/orthogonal-planes#2]
The header is fine but the rest is unreadable. Looks like it is partially compressed but zip7 does not recognize. Could you guys check for me?

Thanks!

**Comment by c-sommer** [comment]
Hi! The `.ply` file is in binary format, i.e. only the header will be human-readable. You can use Meshlab, Matlabs `pcread` command or the C++ [tinyply](https://github.com/ddiakopoulos/tinyply) libary that is also used in this repository (see [load_ply_cloud.h](https://github.com/c-sommer/orthogonal-planes/blob/master/include/io/load_ply_cloud.h)) to load and further process the point cloud.
