### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by HU-517** [c-sommer/orthogonal-planes#3]
/home/hu/Software/orthogonal-planes-master/include/visualize/draw_lines.h:47:9: error: ‘glDrawColoredVertices’ is not a member of ‘pangolin’
         pangolin::glDrawColoredVertices<double, double>(2, verts, cols, GL_LINES, 3, 3);
         ^
/home/hu/Software/orthogonal-planes-master/include/visualize/draw_lines.h:47:41: error: expected primary-expression before ‘double’
         pangolin::glDrawColoredVertices<double, double>(2, verts, cols, GL_LINES, 3, 3);

**Comment by c-sommer** [comment]
Dear Hu,
I have never encountered this error (using Ubuntu 18.04 and g++), I thus suspect that Pangolin might not be installed and/or linked correctly in your setup. Note that I used the Pangolin version that is added as a submodule in the folder `3rdParty`. If you are using a more recent one, this might be what causes the error.
Best,
Christiane

**Comment by HU-517** [comment]
Can you tell me about your version of the g++?Can the version of the third-party library also tell it if it is convenient?

**Comment by c-sommer** [comment]
The g++ version under which the code is confirmed to work was 7.5 (Ubuntu 18.04).
For the `3rdParty` folder, please refer directly to the versions that are included as submodules in the folder (e.g. for Pangolin, that is [Pangolin @ b6cecf4](https://github.com/stevenlovegrove/Pangolin/tree/b6cecf4e5faaa9cf6039f98c8d263cbc169f0b5d)).
